-- CORREÇÃO SOMATIVA 01 - OFICINA MECÂNICA
create database if not exists oficina_oricolli3;

use oficina_oricolli3;

create table if not exists clientes (
    id_cliente int AUTO_INCREMENT primary key,
    nome_cliente varchar(60) not NULL,
    telefone CHAR(15) not NULL,
    email varchar(100) not NULL,
    cpf char(14) not null UNIQUE,
    data_nascimento date not null,
    status_cliente ENUM('Ativo', 'Inativo') default 'Ativo',
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE Table if NOT exists veiculos(
    id_veiculos INT AUTO_INCREMENT primary KEY,
    placa CHAR(8) not NULL UNIQUE,
    tipo_veiculo ENUM('Carro', 'Moto', 'Caminhão') DEFAULT ('Carro'),
    cor VARCHAR(20),
    quilometragem FLOAT,
    tipo_motor enum ('Eletrico', 'Combustao'),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

create TABLE if not exists marcas(
    id_marca int AUTO_INCREMENT primary KEY,
    ano_lancamento year,
    pais_origem VARCHAR(60),
    status_marca enum('Ativo', 'Inativo') DEFAULT ('Ativo'),
    nome_marca varchar(30) not NULL,
    SITE_MARCA VARCHAR(100)
) ;

CREATE TABLE IF NOT EXISTS MODELOS(
    ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
    COR VARCHAR(20),
    ANO_MODELO YEAR,
    VALOR_MODELO DECIMAL (10,2) NOT NULL,
    CATEGORIA ENUM ('SUV', 'HATCH', 'SEDAN', 'MOTO ESPORTIVA'),
    NOME_MODELO VARCHAR (60),
    STATUS_MODELO ENUM ('ATIVO', 'iNATIVO'), 
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CPF_FUNCIONARIO CHAR(14) UNIQUE NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    STATUS_FUNCIONARIO ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO'    
);


CREATE TABLE IF NOT EXISTS SERVICOS (
    ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_SERVICO VARCHAR(60) NOT NULL,
    DESCRICAO_PROBLEMA VARCHAR(250) NOT NULL,
    PRECO_SERVICO DECIMAL (10,2) DEFAULT 0.00 NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    STATUS_SERVICO ENUM ('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PECAS(
    ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
    TAMANHO VARCHAR(10) NOT NULL,
    VALOR_PECA DECIMAL(10,2) NOT NULL,
    NOME_PECA VARCHAR(50) NOT NULL,
    VALIDAE DATE NOT NULL,
    STATUS_PECA ENUM ('DISPONIVEL', 'INDISPONIVEL'),
    QTDE_PECAS INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVICO(
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    PRIORIDADE ENUM ('URGENTE','SIMPLES') NOT NULL DEFAULT 'SIMPLES',
    PRAZO_FINAL DATE NOT NULL,
    RANKING_ORDEM VARCHAR(50) NOT NULL,
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_CASO VARCHAR(250) NOT NULL,
    STATUS_ORDEM_SERVICO ENUM('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE'
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 00.0,
    FORMA_PAGAMENTO ENUM ('DEBITO', 'CREDITO', 'PIX') DEFAULT 'PIX' NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    STATUS_PAGAMENTO ENUM ('PAGO', 'PENDENTE') DEFAULT 'PENDENTE',
    COMPROVANTE INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    CNPJ CHAR(18) NOT NULL UNIQUE,
    TELEFONE_CONTATO VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    INSCRICAO_ESTADUAL CHAR(10),
    SEGMENTO_FORNECEDOR VARCHAR(50) NOT NULL,
    ENDERECO_FORNECEDOR VARCHAR(100) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTERAÇÕES INSERINDO CAMPOS NOVOS NAS TABELAS
ALTER TABLE CLIENTES ADD IDADE INT;
ALTER TABLE FUNCIONARIOS ADD ENDERECO VARCHAR(100);
ALTER TABLE marcas ADD OBSERVACAO VARCHAR(200);
ALTER TABLE MODELOS ADD TIPO_MODELO VARCHAR(50);
ALTER TABLE ORDEM_DE_SERVICO ADD AREA_SERVICO VARCHAR(60) NOT NULL;
ALTER TABLE PECAS ADD PESO FLOAT NOT NULL;
ALTER TABLE SERVICOS ADD OBSERVACAO VARCHAR(60); 
ALTER TABLE VEICULOS ADD MODELO VARCHAR(50); 
ALTER TABLE FORNECEDOR ADD TIPO_ENVIO VARCHAR(100); 
ALTER TABLE PAGAMENTOS ADD DESCONTO DECIMAL(10,2) DEFAULT 0.00 NOT NULL;

-- EXCLUSÃO DE CAMPOS NAS TABELAS

ALTER TABLE CLIENTES DROP COLUMN IDADE;

-- RENOMEAR TABELA

RENAME TABLE MODELOS TO MODELOS_FAB;

-- VISUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- VISUALIZAR TABELAS DO BD
SHOW TABLES;

-- DESCRIÇÃO SOBRE INFORMAÇÕES DAS TABELAS
DESCRIBE CLIENTES;